name: Logik Version Control Demo 
on:
   push: 
     branches: 
       - "main"
jobs: 
 To-Zip: 
   runs-on: ubuntu-latest 
   steps: 
     - name: Checkout 
       uses: actions/checkout@v3 
     - name: whereAmI 
       run: ls 
     - name: zip 
       run: zip -r -q Archive.zip blueprints fields rules blueprint.yaml 
     - name: whereAmI1 
       run: ls 
     - name: runUpload 
       run: python upload.py
