on:
  workflow_dispatch:
    inputs:
      NAME:
        description: "A random input name for the workflow"
        type: string
jobs:
  pull_bp:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: start_export_blueprint
        run: |
          wget --header="accept: application/json" \
            --header="content-type: application/json" \
            --header='Authorization: Bearer ${{ secrets.LOGIK_SOURCE_API }}' \
            --compression=auto \
            --post-data='["${{ github.event.inputs.NAME }}"]' \
            --output-document=exportJob.json \
            https://sam-dev-demo.dev.logik.io/api/admin/v1/bulk/blueprints/export

      - name: get_job_id
        id: get_job_id
        run: echo "JOB_ID=$(jq .id exportJob.json)" >> $GITHUB_OUTPUT
      - name: generate_export_url
        id: generate_export_url
        run: echo "EXPORT_URL=https://sam-dev-demo.dev.logik.io/api/admin/v2/bulk/export/${{ steps.get_job_id.outputs.JOB_ID }}" >> $GITHUB_OUTPUT
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: "30s"

      - name: download_blueprint
        run: |
          wget --header="accept: application/octet-stream" \
            --header="Authorization: Bearer ${{ secrets.LOGIK_SOURCE_API }}" \
            --compression=auto \
            --output-document=export.zip \
            ${{ steps.generate_export_url.outputs.EXPORT_URL }}

      - name: extract_blueprint
        run: mkdir temp_extract && unzip export.zip -d temp_extract

      - name: upload_commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "temp_extract"
          message: "blueprint"
          author_name: Sam Check
          author_email: scheck@logik.io
          new_branch: ${{ github.event.inputs.NAME }}
