on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run every hour
    - cron:  '0 * * * *'
jobs: 
 pull_bp: 
   runs-on: ubuntu-latest 
   steps: 
     - name: Branch 
       uses: actions/checkout@v3 
     - name: start_export_blueprint 
       run: |
        curl 'https://sam-dev-demo.dev.logik.io/api/admin/v1/bulk/blueprints/export' \
         -X POST \
         -H 'accept: application/json' \
         -H 'content-type: application/json' \
         -H 'Authorization: Bearer ${{ secrets.LOGIK_SOURCE_API}}'\
         -d '["pCBuilder"]' \
         --compressed \
        | jq .id >> "$GITHUB_OUTPUT"

     - name:  echo_out
       run: echo {{steps.start_export_blueprint.output}}
     - name: Sleep for 30 seconds
       uses: jakejarvis/wait-action@master
       with:
         time: '30s'
