name: Logik Push Blueprint
on:
   workflow_dispatch
jobs: 
 To-Zip: 
   runs-on: ubuntu-latest 
   steps: 
jobs:
  To-Zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: CreateZip
        run: zip -r -q archive.zip *
